name: Lint

on:
    push:
      branches:
      - main
    pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@protoc
    - uses: dtolnay/rust-toolchain@beta
      with:
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: rustfmt
      run: cargo fmt --all --check
